/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import static java.awt.Color.red;

/**
 *
 * @author ADMIN
 */
public class frmBanAn extends javax.swing.JFrame {

    /**
     * Creates new form frmBanAn
     */
    public frmBanAn() {
        initComponents();
    }
    
    public void CoKhach(String soban){
        if(soban == "01")
            this.btnBan01.setBackground(Color.red);
        else if(soban == "02")
            this.btnBan02.setBackground(Color.red);
        else if(soban == "03")
            this.btnBan03.setBackground(Color.red);
        else if(soban == "04")
            this.btnBan04.setBackground(Color.red);
        else if(soban == "05")
            this.btnBan05.setBackground(Color.red);
        else if(soban == "06")
            this.btnBan06.setBackground(Color.red);
        else if(soban == "07")
            this.btnBan07.setBackground(Color.red);
        else if(soban == "08")
            this.btnBan08.setBackground(Color.red);
        else if(soban == "09")
            this.btnBan09.setBackground(Color.red);
        else if(soban == "10")
            this.btnBan10.setBackground(Color.red);
        else if(soban == "11")
            this.btnBan11.setBackground(Color.red);
        else if(soban == "12")
            this.btnBan12.setBackground(Color.red);
    }
    
    public void VangKhach(String soban){
        if(soban == "01")
            this.btnBan01.setBackground(Color.green);
        else if(soban == "02")
            this.btnBan02.setBackground(Color.green);
        else if(soban == "03")
            this.btnBan03.setBackground(Color.green);
        else if(soban == "04")
            this.btnBan04.setBackground(Color.green);
        else if(soban == "05")
            this.btnBan05.setBackground(Color.green);
        else if(soban == "06")
            this.btnBan06.setBackground(Color.green);
        else if(soban == "07")
            this.btnBan07.setBackground(Color.green);
        else if(soban == "08")
            this.btnBan08.setBackground(Color.green);
        else if(soban == "09")
            this.btnBan09.setBackground(Color.green);
        else if(soban == "10")
            this.btnBan10.setBackground(Color.green);
        else if(soban == "11")
            this.btnBan11.setBackground(Color.green);
        else if(soban == "12")
            this.btnBan12.setBackground(Color.green);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBan01 = new javax.swing.JButton();
        btnBan04 = new javax.swing.JButton();
        btnBan02 = new javax.swing.JButton();
        btnBan07 = new javax.swing.JButton();
        btnBan03 = new javax.swing.JButton();
        btnBan05 = new javax.swing.JButton();
        btnBan06 = new javax.swing.JButton();
        btnBan08 = new javax.swing.JButton();
        btnBan11 = new javax.swing.JButton();
        btnBan12 = new javax.swing.JButton();
        btnBan10 = new javax.swing.JButton();
        btnBan09 = new javax.swing.JButton();
        btnTrong = new javax.swing.JButton();
        btnCo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chọn bàn ăn");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bàn ăn");

        btnBan01.setBackground(new java.awt.Color(0, 255, 0));
        btnBan01.setText("Bàn 01");
        btnBan01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan01ActionPerformed(evt);
            }
        });

        btnBan04.setBackground(new java.awt.Color(0, 255, 0));
        btnBan04.setText("Bàn 04");
        btnBan04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan04ActionPerformed(evt);
            }
        });

        btnBan02.setBackground(new java.awt.Color(0, 255, 0));
        btnBan02.setText("Bàn 02");
        btnBan02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan02ActionPerformed(evt);
            }
        });

        btnBan07.setBackground(new java.awt.Color(0, 255, 0));
        btnBan07.setText("Bàn 07");
        btnBan07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan07ActionPerformed(evt);
            }
        });

        btnBan03.setBackground(new java.awt.Color(0, 255, 0));
        btnBan03.setText("Bàn 03");
        btnBan03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan03ActionPerformed(evt);
            }
        });

        btnBan05.setBackground(new java.awt.Color(0, 255, 0));
        btnBan05.setText("Bàn 05");
        btnBan05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan05ActionPerformed(evt);
            }
        });

        btnBan06.setBackground(new java.awt.Color(0, 255, 0));
        btnBan06.setText("Bàn 06");
        btnBan06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan06ActionPerformed(evt);
            }
        });

        btnBan08.setBackground(new java.awt.Color(0, 255, 0));
        btnBan08.setText("Bàn 08");
        btnBan08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan08ActionPerformed(evt);
            }
        });

        btnBan11.setBackground(new java.awt.Color(0, 255, 0));
        btnBan11.setText("Bàn 11");
        btnBan11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan11ActionPerformed(evt);
            }
        });

        btnBan12.setBackground(new java.awt.Color(0, 255, 0));
        btnBan12.setText("Bàn 12");
        btnBan12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan12ActionPerformed(evt);
            }
        });

        btnBan10.setBackground(new java.awt.Color(0, 255, 0));
        btnBan10.setText("Bàn 10");
        btnBan10.setVerifyInputWhenFocusTarget(false);
        btnBan10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan10ActionPerformed(evt);
            }
        });

        btnBan09.setBackground(new java.awt.Color(0, 255, 0));
        btnBan09.setText("Bàn 09");
        btnBan09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBan09ActionPerformed(evt);
            }
        });

        jLabel2.setText("Trống");

        jLabel3.setText("Có Khách");

        jMenu1.setText("Hệ thống");

        jMenuItem1.setText("Đăng xuất");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Thoát");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBan04, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnBan01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBan07, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBan10, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBan08, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBan11, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBan09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBan12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBan02, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(btnBan05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBan06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBan03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))))
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBan02, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan03, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan01, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBan06, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBan04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBan05, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBan08, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBan07, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBan09, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnBan12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBan11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBan10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBan01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan01ActionPerformed
        // TODO add your handling code here:
        String SoBan = "01";
        frmChonMon chonmon = new frmChonMon();
        chonmon.banan = this;
        chonmon.SB(SoBan);
        chonmon.setVisible(true);

    }//GEN-LAST:event_btnBan01ActionPerformed

    private void btnBan02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan02ActionPerformed
        // TODO add your handling code here:
        String SoBan = "02";
        frmChonMon chonmon = new frmChonMon();
        chonmon.banan = this;
        chonmon.SB(SoBan);
        chonmon.setVisible(true);
    }//GEN-LAST:event_btnBan02ActionPerformed

    private void btnBan03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan03ActionPerformed
        // TODO add your handling code here:
        String SoBan = "03";
        frmChonMon chonmon = new frmChonMon();
        chonmon.banan = this;
        chonmon.SB(SoBan);
        chonmon.setVisible(true);
        
    }//GEN-LAST:event_btnBan03ActionPerformed

    private void btnBan04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan04ActionPerformed
        // TODO add your handling code here:
        String SoBan = "04";
        frmChonMon chonmon = new frmChonMon();
        chonmon.banan = this;
        chonmon.SB(SoBan);
        chonmon.setVisible(true);
    }//GEN-LAST:event_btnBan04ActionPerformed

    private void btnBan05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan05ActionPerformed
        // TODO add your handling code here:
        String SoBan = "05";
        frmChonMon chonmon = new frmChonMon();
        chonmon.banan = this;
        chonmon.SB(SoBan);
        chonmon.setVisible(true);
    }//GEN-LAST:event_btnBan05ActionPerformed

    private void btnBan06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan06ActionPerformed
        // TODO add your handling code here:
        String SoBan = "06";
        frmChonMon chonmon = new frmChonMon();
        chonmon.banan = this;
        chonmon.SB(SoBan);
        chonmon.setVisible(true);
    }//GEN-LAST:event_btnBan06ActionPerformed

    private void btnBan07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan07ActionPerformed
        // TODO add your handling code here:
        String SoBan = "07";
        frmChonMon chonmon = new frmChonMon();
        chonmon.banan = this;
        chonmon.SB(SoBan);
        chonmon.setVisible(true);
    }//GEN-LAST:event_btnBan07ActionPerformed

    private void btnBan08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan08ActionPerformed
        // TODO add your handling code here:
        String SoBan = "08";
        frmChonMon chonmon = new frmChonMon();
        chonmon.banan = this;
        chonmon.SB(SoBan);
        chonmon.setVisible(true);
    }//GEN-LAST:event_btnBan08ActionPerformed

    private void btnBan09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan09ActionPerformed
        // TODO add your handling code here:
        String SoBan = "09";
        frmChonMon chonmon = new frmChonMon();
        chonmon.banan = this;
        chonmon.SB(SoBan);
        chonmon.setVisible(true);
    }//GEN-LAST:event_btnBan09ActionPerformed

    private void btnBan10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan10ActionPerformed
        // TODO add your handling code here:
        String SoBan = "10";
        frmChonMon chonmon = new frmChonMon();
        chonmon.banan = this;
        chonmon.SB(SoBan);
        chonmon.setVisible(true);
    }//GEN-LAST:event_btnBan10ActionPerformed

    private void btnBan11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan11ActionPerformed
        // TODO add your handling code here:
        String SoBan = "11";
        frmChonMon chonmon = new frmChonMon();
        chonmon.banan = this;
        chonmon.SB(SoBan);
        chonmon.setVisible(true);
    }//GEN-LAST:event_btnBan11ActionPerformed

    private void btnBan12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBan12ActionPerformed
        // TODO add your handling code here:
        String SoBan = "12";
        frmChonMon chonmon = new frmChonMon();
        chonmon.banan = this;
        chonmon.SB(SoBan);
        chonmon.setVisible(true);
    }//GEN-LAST:event_btnBan12ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.btnTrong.setBackground(Color.GREEN);
        this.btnCo.setBackground(red);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        frmLuaChonNguoiDung chon = new frmLuaChonNguoiDung();
        chon.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBanAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBanAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBanAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBanAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBanAn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBan01;
    private javax.swing.JButton btnBan02;
    private javax.swing.JButton btnBan03;
    private javax.swing.JButton btnBan04;
    private javax.swing.JButton btnBan05;
    private javax.swing.JButton btnBan06;
    private javax.swing.JButton btnBan07;
    private javax.swing.JButton btnBan08;
    private javax.swing.JButton btnBan09;
    private javax.swing.JButton btnBan10;
    private javax.swing.JButton btnBan11;
    private javax.swing.JButton btnBan12;
    private javax.swing.JButton btnCo;
    private javax.swing.JButton btnTrong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
