/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.clssDoUong;
import Model.clssMonAn;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class frmChonMon extends javax.swing.JFrame {

    
    public frmBanAn banan;
    /**
     * Creates new form frmChonMon
     */
    
    public void SB(String soban){
        this.txtSoBan.setText(soban);
    }
    
    public frmChonMon() {
        initComponents();
        HienThiDSMonAn();
        HienThiDSDoUong();
//        HienThiDSHoaDon();
    }
    
    public void HienThiDSMonAn(){
        Vector<clssMonAn> ds = new Vector<clssMonAn>();
        
        int ketqua = CSDL.tbMonAn.LayDSMonAn(ds);
        if(ketqua == -1){
            JOptionPane.showMessageDialog(this, "Loi ket noi sql");
            return;
        }
        else if(ketqua == -2){
            JOptionPane.showMessageDialog(this, "Loi sql");
            return;
        }
        else{
            DefaultTableModel dtm = (DefaultTableModel)this.tblMonAn.getModel();
            dtm.setRowCount(0);
            for(clssMonAn dss : ds)
                dtm.addRow(new Object[] {dss.getTenMonAn(), dss.getDonGia()});
        }
    }
    
    public void HienThiDSDoUong(){
        Vector<clssDoUong> ds = new Vector<clssDoUong>();
        
        int ketqua = CSDL.tbDoUong.LayDSDoUong(ds);
        if(ketqua == -1){
            JOptionPane.showMessageDialog(this, "Loi ket noi sql");
            return;
        }
        else if(ketqua == -2){
            JOptionPane.showMessageDialog(this, "Loi sql");
            return;
        }
        else{
            DefaultTableModel dtm = (DefaultTableModel)this.tblDoUong.getModel();
            dtm.setRowCount(0);
            for(clssDoUong dss : ds)
                dtm.addRow(new Object[] {dss.getTenDoUong(), dss.getDonGia()});
        }
    }
    
    public void HienThiDSHoaDon(){
        Connection conn = CSDL.Database.KetNoiCSDL();
        if(conn == null)
        {
            JOptionPane.showMessageDialog(this, "Loi ket noi");
            return;
        }
        String soban = this.txtSoBan.getText();
        String sql = "select * from hoadon_ban_" + soban;
        
        
        try {
            PreparedStatement stm = conn.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel)this.tblHoaDon.getModel();
            dtm.setNumRows(0);
            while(rs.next()){
                int id = rs.getInt("id");
                String ten = rs.getString("ten");
                float dongia = rs.getFloat("dongia");
                int soluong = rs.getInt("soluong");
                float thanhtien = rs.getFloat("thanhtien"); 
                dtm.addRow(new Object[] {id, ten, Float.toString(dongia), Integer.toString(soluong), Float.toString(thanhtien)});
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(frmChonMon.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Loi sql " + ex.getMessage());
            return;
        }
    }
    
    public boolean ktso(String so){
        try{
            float i = Float.parseFloat(so);
            return true;
        }
        catch(Exception ex){
            return false;
        }
    }
    
    public float TongTien(){
        String tt = this.txtTongTien.getText();
        float tongtien = Float.parseFloat(tt);
        return tongtien;
    }

    public int SoBan(){
        String soban = this.txtSoBan.getText();
        int SB = Integer.parseInt(soban);
        return SB;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMonAn = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDoUong = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTenMonAn = new javax.swing.JTextField();
        txtDonGiaMonAn = new javax.swing.JTextField();
        txtSoLuongMonAn = new javax.swing.JTextField();
        txtThanhTienMonAn = new javax.swing.JTextField();
        txtTenDoUong = new javax.swing.JTextField();
        txtDonGiaDoUong = new javax.swing.JTextField();
        txtSoLuongDoUong = new javax.swing.JTextField();
        txtThanhTienDoUong = new javax.swing.JTextField();
        btnThemMonHoaDon = new javax.swing.JButton();
        btnThemDoUongHoaDon = new javax.swing.JButton();
        btnThanhTienMonAn = new javax.swing.JButton();
        btnThanhTienDoUong = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        btnLamMoiMonAn = new javax.swing.JButton();
        btnLamMoiDoUong = new javax.swing.JButton();
        btnTongTien = new javax.swing.JButton();
        txtTongTien = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSoBan = new javax.swing.JLabel();
        btnDSHoaDon = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHỌN MÓN");

        tblMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên món ăn", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMonAnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMonAn);

        tblDoUong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên đồ uống", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDoUongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDoUong);

        jLabel2.setText("Tên món ăn:");

        jLabel3.setText("Đơn giá:");

        jLabel4.setText("Số lượng:");

        jLabel6.setText("Tên đồ uống:");

        jLabel7.setText("Đơn giá:");

        jLabel8.setText("Số lượng:");

        txtTenMonAn.setEditable(false);

        txtDonGiaMonAn.setEditable(false);

        txtThanhTienMonAn.setEditable(false);

        txtTenDoUong.setEditable(false);

        txtDonGiaDoUong.setEditable(false);

        txtThanhTienDoUong.setEditable(false);

        btnThemMonHoaDon.setText("Thêm vào hóa đơn");
        btnThemMonHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMonHoaDonActionPerformed(evt);
            }
        });

        btnThemDoUongHoaDon.setText("Thêm vào hóa đơn");
        btnThemDoUongHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDoUongHoaDonActionPerformed(evt);
            }
        });

        btnThanhTienMonAn.setText("Thành tiền:");
        btnThanhTienMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhTienMonAnActionPerformed(evt);
            }
        });

        btnThanhTienDoUong.setText("Thành tiền:");
        btnThanhTienDoUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhTienDoUongActionPerformed(evt);
            }
        });

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblHoaDon);

        btnLamMoiMonAn.setText("Làm mới");
        btnLamMoiMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiMonAnActionPerformed(evt);
            }
        });

        btnLamMoiDoUong.setText("Làm mới");
        btnLamMoiDoUong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiDoUongActionPerformed(evt);
            }
        });

        btnTongTien.setText("Tổng tiền");
        btnTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTongTienActionPerformed(evt);
            }
        });

        txtTongTien.setEditable(false);

        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("BÀN:");

        txtSoBan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSoBan.setForeground(new java.awt.Color(0, 0, 255));
        txtSoBan.setText("Số bàn");

        btnDSHoaDon.setText("Lấy danh sách hóa đơn");
        btnDSHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSHoaDonActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jButton1.setText("Xóa hết danh sách");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        jMenu1.setText("Hệ thống");

        jMenuItem1.setText("Quay lại");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Đăng xuất");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Thoát");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(btnThanhTienMonAn))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTenMonAn)
                                            .addComponent(txtDonGiaMonAn)
                                            .addComponent(txtSoLuongMonAn)
                                            .addComponent(txtThanhTienMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThemMonHoaDon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnLamMoiMonAn))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThemDoUongHoaDon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                        .addComponent(btnLamMoiDoUong))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(btnThanhTienDoUong))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTenDoUong)
                                            .addComponent(txtDonGiaDoUong)
                                            .addComponent(txtSoLuongDoUong)
                                            .addComponent(txtThanhTienDoUong))))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTongTien)
                                .addGap(18, 18, 18)
                                .addComponent(btnThanhToan))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDSHoaDon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSoBan)
                .addGap(521, 521, 521))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoBan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtTenDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtDonGiaDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtSoLuongDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtThanhTienDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThanhTienDoUong))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnThemDoUongHoaDon)
                                    .addComponent(btnLamMoiDoUong)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDSHoaDon)
                            .addComponent(btnXoa)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDonGiaMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtSoLuongMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtThanhTienMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThanhTienMonAn))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnThemMonHoaDon)
                                    .addComponent(btnLamMoiMonAn)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTongTien)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThanhToan)
                    .addComponent(btnDong))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMonAnMouseClicked
        // TODO add your handling code here:
        int i = this.tblMonAn.getSelectedRow();
        String tenmonan = (String)this.tblMonAn.getValueAt(i, 0);
        float dongia = (float)this.tblMonAn.getValueAt(i, 1);
        
        this.txtTenMonAn.setText(tenmonan);
        this.txtDonGiaMonAn.setText(Float.toString(dongia));
        
        this.txtSoLuongMonAn.setText("1");
        
        this.txtThanhTienMonAn.setText("");
    }//GEN-LAST:event_tblMonAnMouseClicked

    private void tblDoUongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDoUongMouseClicked
        // TODO add your handling code here:
        int i = this.tblDoUong.getSelectedRow();
        String tendouong = (String)this.tblDoUong.getValueAt(i, 0);
        float dongia = (float)this.tblDoUong.getValueAt(i, 1);
        
        this.txtTenDoUong.setText(tendouong);
        this.txtDonGiaDoUong.setText(Float.toString(dongia));
        
        this.txtSoLuongDoUong.setText("1");
        
        this.txtThanhTienDoUong.setText("");
    }//GEN-LAST:event_tblDoUongMouseClicked

    private void btnThanhTienMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhTienMonAnActionPerformed
        // TODO add your handling code here:
        String soluong = this.txtSoLuongMonAn.getText();
        String monan = this.txtTenMonAn.getText();
        if(monan.equals("")){
            JOptionPane.showMessageDialog(this, "Chưa chọn món");
            return;
        }
        if(soluong.equals("")){
            JOptionPane.showMessageDialog(this, "Chưa nhập số lượng");
            return;
        }
        if(ktso(soluong) == false){
            JOptionPane.showMessageDialog(this, "Số lượng phải là số");
            return;
        }
        float dongia = Float.parseFloat(this.txtDonGiaMonAn.getText());
        int sl = Integer.parseInt(soluong);
        this.txtThanhTienMonAn.setText(Float.toString(dongia * sl));
        
    }//GEN-LAST:event_btnThanhTienMonAnActionPerformed

    private void btnThanhTienDoUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhTienDoUongActionPerformed
        // TODO add your handling code here:
        String soluong = this.txtSoLuongDoUong.getText();
        String douong = this.txtTenDoUong.getText();
        if(douong.equals("")){
            JOptionPane.showMessageDialog(this, "Chưa chọn đồ uống");
            return;
        }
        if(soluong.equals("")){
            JOptionPane.showMessageDialog(this, "Chưa nhập số lượng");
            return;
        }
        if(ktso(soluong) == false){
            JOptionPane.showMessageDialog(this, "Số lượng phải là số");
            return;
        }
        float dongia = Float.parseFloat(this.txtDonGiaDoUong.getText());
        int sl = Integer.parseInt(soluong);
        this.txtThanhTienDoUong.setText(Float.toString(dongia * sl));
    }//GEN-LAST:event_btnThanhTienDoUongActionPerformed

    private void btnThemMonHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMonHoaDonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)this.tblHoaDon.getModel();
        String ten = this.txtTenMonAn.getText();
        String dongia = this.txtDonGiaMonAn.getText();
        String soluong = this.txtSoLuongMonAn.getText();
        String thanhtien = this.txtThanhTienMonAn.getText();
        
        if(thanhtien.equals("")){
            JOptionPane.showMessageDialog(this, "Chưa thành tiền");
            return;
        }
        
        Connection conn = CSDL.Database.KetNoiCSDL();
        if(conn == null)
        {
            JOptionPane.showMessageDialog(this, "Loi ket noi");
            return;
        }
        String soban = this.txtSoBan.getText();
        String sql = "insert into hoadon_ban_" + soban + "(ID, Ten, DonGia, SoLuong, ThanhTien) "
                + " values(NULL, ?, ?, ?, ?)";

            PreparedStatement stm;
        try {
            stm = conn.prepareStatement(sql);
            stm.setString(1, ten);
            stm.setFloat(2, Float.parseFloat(dongia));
            stm.setInt(3, Integer.parseInt(soluong));
            stm.setFloat(4, Float.parseFloat(thanhtien));
 
            int n = stm.executeUpdate();
            if(n>0){
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmChonMon.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Loi sql " + ex.getMessage());
            return;
        }
        
        HienThiDSHoaDon();
          
        this.txtTenMonAn.setText("");
        this.txtDonGiaMonAn.setText("");
        this.txtSoLuongMonAn.setText("");
        this.txtThanhTienMonAn.setText("");
        
        HienThiDSMonAn();
        
    }//GEN-LAST:event_btnThemMonHoaDonActionPerformed

    private void btnLamMoiMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiMonAnActionPerformed
        // TODO add your handling code here:
        this.txtTenMonAn.setText("");
        this.txtDonGiaMonAn.setText("");
        this.txtSoLuongMonAn.setText("");
        this.txtThanhTienMonAn.setText("");
        
        HienThiDSMonAn();
    }//GEN-LAST:event_btnLamMoiMonAnActionPerformed

    private void btnLamMoiDoUongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiDoUongActionPerformed
        // TODO add your handling code here:
        this.txtTenDoUong.setText("");
        this.txtDonGiaDoUong.setText("");
        this.txtSoLuongDoUong.setText("");
        this.txtThanhTienDoUong.setText("");
        
        HienThiDSDoUong();
    }//GEN-LAST:event_btnLamMoiDoUongActionPerformed

    private void btnThemDoUongHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDoUongHoaDonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)this.tblHoaDon.getModel();
        String ten = this.txtTenDoUong.getText();
        String dongia = this.txtDonGiaDoUong.getText();
        String soluong = this.txtSoLuongDoUong.getText();
        String thanhtien = this.txtThanhTienDoUong.getText();
        
        if(thanhtien.equals("")){
            JOptionPane.showMessageDialog(this, "Chưa thành tiền");
            return;
        }
        
        Connection conn = CSDL.Database.KetNoiCSDL();
        if(conn == null)
        {
            JOptionPane.showMessageDialog(this, "Loi ket noi");
            return;
        }
        String soban = this.txtSoBan.getText();
        String sql = "insert into hoadon_ban_" + soban + "(ID, Ten, DonGia, SoLuong, ThanhTien) "
                + " values(NULL, ?, ?, ?, ?)";

            PreparedStatement stm;
        try {
            stm = conn.prepareStatement(sql);
            stm.setString(1, ten);
            stm.setFloat(2, Float.parseFloat(dongia));
            stm.setInt(3, Integer.parseInt(soluong));
            stm.setFloat(4, Float.parseFloat(thanhtien));
            
            int n = stm.executeUpdate();
            if(n>0){
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(frmChonMon.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Loi sql " + ex.getMessage());
            return;
        }
        
        HienThiDSHoaDon();
        
        this.txtTenDoUong.setText("");
        this.txtDonGiaDoUong.setText("");
        this.txtSoLuongDoUong.setText("");
        this.txtThanhTienDoUong.setText("");
        
        HienThiDSDoUong();
    }//GEN-LAST:event_btnThemDoUongHoaDonActionPerformed

    private void btnTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTongTienActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel)this.tblHoaDon.getModel();
        int row = dtm.getRowCount();
        float tongtien = 0f;
        for (int i = 0; i < row; i++) {
            String x = (String)this.tblHoaDon.getValueAt(i, 4);
            float xx = Float.parseFloat(x);
            tongtien += xx;
        }
        this.txtTongTien.setText(Float.toString(tongtien));
        
        for (int i = 0; i < row; i++) {
            String ten = (String)this.tblHoaDon.getValueAt(i, 1);
            String dongia = (String)this.tblHoaDon.getValueAt(i, 2);
            String soluong = (String)this.tblHoaDon.getValueAt(i, 3);
            String thanhtien = (String)this.tblHoaDon.getValueAt(i, 4);

            Connection conn = CSDL.Database.KetNoiCSDL();
            if(conn == null)
            {
                JOptionPane.showMessageDialog(this, "Loi ket noi");
                return;
            }
            String sql = "insert into thong_ke(ID, Ten, DonGia, SoLuong, ThanhTien) "
                    + " values(NULL, ?, ?, ?, ?)";

                PreparedStatement stm;
            try {
                stm = conn.prepareStatement(sql);
                stm.setString(1, ten);
                stm.setFloat(2, Float.parseFloat(dongia));
                stm.setInt(3, Integer.parseInt(soluong));
                stm.setFloat(4, Float.parseFloat(thanhtien));
                stm.executeUpdate();

            } catch (SQLException ex) {
                Logger.getLogger(frmChonMon.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Loi sql " + ex.getMessage());
                return;
            }
        }    
    }//GEN-LAST:event_btnTongTienActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        String tt = this.txtTongTien.getText();
        if(tt.equals("") || Float.parseFloat(tt) == 0){
            JOptionPane.showMessageDialog(this, "Thanh toán thất bại");
            return;
        }
        frmThanhToan thanhtoan = new frmThanhToan();
        thanhtoan.chonmon = this;
        thanhtoan.SB(this.txtSoBan.getText());
        thanhtoan.setVisible(true);
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowOpened

    private void btnDSHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSHoaDonActionPerformed
        // TODO add your handling code here:
        HienThiDSHoaDon();
    }//GEN-LAST:event_btnDSHoaDonActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int i = this.tblHoaDon.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(this, "Chưa chọn món cần xóa");
            return;
        }
        else{
            Connection cnn = CSDL.Database.KetNoiCSDL();
            if(cnn == null){
                JOptionPane.showMessageDialog(this, "Ket noi that bai !!!");
                return;
            }
            String soban = this.txtSoBan.getText();
            String sql = "DELETE FROM hoadon_ban_" + soban 
                    + " WHERE ID=?";
            try {
                DefaultTableModel dtm = (DefaultTableModel)this.tblHoaDon.getModel();
                int id = (int)dtm.getValueAt(i, 0);
                PreparedStatement stm = cnn.prepareStatement(sql);
                stm.setInt(1, id);
                int n = stm.executeUpdate();
                if(n>0){
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    HienThiDSHoaDon();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Loi SQL");
                Logger.getLogger(frmChonMon.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            
    }//GEN-LAST:event_btnXoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection conn = CSDL.Database.KetNoiCSDL();
        if(conn == null)
        {
            JOptionPane.showMessageDialog(this, "Loi ket noi");
            return;
        }
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn sẽ bị mất hết dữ liệu.\nChắc chắn xóa ??", "Thông báo !!!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(hoi == JOptionPane.YES_OPTION){
            String soban = this.txtSoBan.getText();
            String sql = "delete from hoadon_ban_" + soban;

            try {
                PreparedStatement stm = conn.prepareStatement(sql);
                int n = stm.executeUpdate();
                if(n>0){
                    JOptionPane.showMessageDialog(this, "Xóa hết thành công");
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmThanhToan.class.getName()).log(Level.SEVERE, null, ex);
            }

            String sqll = "ALTER TABLE hoadon_ban_" + soban + " AUTO_INCREMENT = 1";

            try {
                PreparedStatement stm = conn.prepareStatement(sqll);
                stm.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(frmThanhToan.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Lôi sql " + ex.getMessage());
            }
            HienThiDSHoaDon();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        Connection conn = CSDL.Database.KetNoiCSDL();
        if(conn == null)
        {
            JOptionPane.showMessageDialog(this, "Loi ket noi");
            return;
        }
        String soban = this.txtSoBan.getText();
        String sql = "select * from hoadon_ban_" + soban;
        
        try {
            PreparedStatement stm = conn.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel)this.tblHoaDon.getModel();
            dtm.setNumRows(0);
            int dem = 0;
            while(rs.next()){
                dem ++;
            }
            if(dem == 0){
                banan.VangKhach(soban);
                this.dispose();
            }
            else{
                banan.CoKhach(soban);
                this.dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmChonMon.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Loi sql " + ex.getMessage());
            return;
        }
        
    }//GEN-LAST:event_btnDongActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Connection conn = CSDL.Database.KetNoiCSDL();
        if(conn == null)
        {
            JOptionPane.showMessageDialog(this, "Loi ket noi");
            return;
        }
        String soban = this.txtSoBan.getText();
        String sql = "select * from hoadon_ban_" + soban;
        
        try {
            PreparedStatement stm = conn.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel)this.tblHoaDon.getModel();
            dtm.setNumRows(0);
            int dem = 0;
            while(rs.next()){
                dem ++;
            }
            if(dem == 0){
                banan.VangKhach(soban);
                this.dispose();
            }
            else{
                banan.CoKhach(soban);
                this.dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmChonMon.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Loi sql " + ex.getMessage());
            return;
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        frmLuaChonNguoiDung chon = new frmLuaChonNguoiDung();
        chon.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChonMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChonMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChonMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChonMon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmChonMon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDSHoaDon;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnLamMoiDoUong;
    private javax.swing.JButton btnLamMoiMonAn;
    private javax.swing.JButton btnThanhTienDoUong;
    private javax.swing.JButton btnThanhTienMonAn;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemDoUongHoaDon;
    private javax.swing.JButton btnThemMonHoaDon;
    private javax.swing.JButton btnTongTien;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblDoUong;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblMonAn;
    private javax.swing.JTextField txtDonGiaDoUong;
    private javax.swing.JTextField txtDonGiaMonAn;
    private javax.swing.JLabel txtSoBan;
    private javax.swing.JTextField txtSoLuongDoUong;
    private javax.swing.JTextField txtSoLuongMonAn;
    private javax.swing.JTextField txtTenDoUong;
    private javax.swing.JTextField txtTenMonAn;
    private javax.swing.JTextField txtThanhTienDoUong;
    private javax.swing.JTextField txtThanhTienMonAn;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
